// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenVpnPilot.Server.Data;

#nullable disable

namespace OpenVpnPilot.Server.Data.Migrations
{
    [DbContext(typeof(PilotServerDbContext))]
    [Migration("20260918090026_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("change_seq");

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChangeSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq");

                    b.Property<string>("Colour")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("colour");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<bool>("HasUnsupportedOptions")
                        .HasColumnType("boolean")
                        .HasColumnName("has_unsupported_options");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<bool?>("ProtectRoutes")
                        .HasColumnType("boolean")
                        .HasColumnName("protect_routes");

                    b.Property<string>("Protocol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("protocol");

                    b.Property<string>("RemoteHost")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remote_host");

                    b.Property<int?>("RemotePort")
                        .HasColumnType("integer")
                        .HasColumnName("remote_port");

                    b.Property<bool>("RequiresCredentials")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_credentials");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("ChangeSeq")
                        .HasDatabaseName("ix_profiles_change_seq");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_content_hash");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.ProfileContent", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<byte[]>("Cipher")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("cipher");

                    b.HasKey("ProfileId")
                        .HasName("pk_profile_contents");

                    b.ToTable("profile_contents", (string)null);
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AuthenticatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authenticated_at");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("PrunedThrough")
                        .HasColumnType("bigint")
                        .HasColumnName("pruned_through");

                    b.HasKey("Id")
                        .HasName("pk_sync_states");

                    b.ToTable("sync_states", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrunedThrough = 0L
                        });
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChangeSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq");

                    b.Property<string>("Colour")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("colour");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("ChangeSeq")
                        .HasDatabaseName("ix_tags_change_seq");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.Tombstone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChangeSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Realm")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("realm");

                    b.HasKey("Id")
                        .HasName("pk_tombstones");

                    b.HasIndex("ChangeSeq")
                        .HasDatabaseName("ix_tombstones_change_seq");

                    b.ToTable("tombstones", (string)null);
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("StateChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_changed_at");

                    b.Property<string>("StateSource")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state_source");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.UserFavourite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int?>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.HasKey("UserId", "ProfileId")
                        .HasName("pk_user_favourites");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_user_favourites_profile_id");

                    b.HasIndex("UserId", "Slot")
                        .IsUnique()
                        .HasDatabaseName("ix_user_favourites_user_id_slot")
                        .HasFilter("slot IS NOT NULL");

                    b.ToTable("user_favourites", (string)null);
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.UserHotkey", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ActionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_id");

                    b.Property<string>("Gesture")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gesture");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("UserId", "ActionId")
                        .HasName("pk_user_hotkeys");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_user_hotkeys_profile_id");

                    b.ToTable("user_hotkeys", (string)null);
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.UserSettingsDocument", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("UserId")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.VaultEntry", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Realm")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("realm");

                    b.Property<long>("ChangeSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq");

                    b.Property<byte[]>("Cipher")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("cipher");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("ProfileId", "Realm")
                        .HasName("pk_vault_entries");

                    b.HasIndex("ChangeSeq")
                        .HasDatabaseName("ix_vault_entries_change_seq");

                    b.ToTable("vault_entries", (string)null);
                });

            modelBuilder.Entity("profile_tags", b =>
                {
                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("uuid")
                        .HasColumnName("profiles_id");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tags_id");

                    b.HasKey("ProfilesId", "TagsId")
                        .HasName("pk_profile_tags");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_profile_tags_tags_id");

                    b.ToTable("profile_tags", (string)null);
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.ProfileContent", b =>
                {
                    b.HasOne("OpenVpnPilot.Server.Data.Entities.Profile", null)
                        .WithOne("Content")
                        .HasForeignKey("OpenVpnPilot.Server.Data.Entities.ProfileContent", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_contents_profiles_profile_id");
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("OpenVpnPilot.Server.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.UserFavourite", b =>
                {
                    b.HasOne("OpenVpnPilot.Server.Data.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_favourites_profiles_profile_id");

                    b.HasOne("OpenVpnPilot.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_favourites_users_user_id");
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.UserHotkey", b =>
                {
                    b.HasOne("OpenVpnPilot.Server.Data.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_hotkeys_profiles_profile_id");

                    b.HasOne("OpenVpnPilot.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_hotkeys_users_user_id");
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.UserSettingsDocument", b =>
                {
                    b.HasOne("OpenVpnPilot.Server.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("OpenVpnPilot.Server.Data.Entities.UserSettingsDocument", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_users_user_id");
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.VaultEntry", b =>
                {
                    b.HasOne("OpenVpnPilot.Server.Data.Entities.Profile", "Profile")
                        .WithMany("VaultEntries")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vault_entries_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("profile_tags", b =>
                {
                    b.HasOne("OpenVpnPilot.Server.Data.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_tags_profiles_profiles_id");

                    b.HasOne("OpenVpnPilot.Server.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_tags_tags_tags_id");
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.Profile", b =>
                {
                    b.Navigation("Content");

                    b.Navigation("VaultEntries");
                });

            modelBuilder.Entity("OpenVpnPilot.Server.Data.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
